name: App Test
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 12.14.0
      uses: actions/setup-node@v3
      with:
        node-version: 12.14.0
    - run: npm i
    - run: npm run build --if-present
    - run: npm test