name: App Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set deploy vars
        id: deploy_vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Check SHA short
        run: echo ${{ steps.deploy_vars.outputs.sha_short }}
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      env:
        ENV: ${{ secrets.ENV }}
        TARGET: ${{ secrets.TARGET }}
        SHA: ${{ steps.deploy_vars.outputs.sha_short }}
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.REMOTE_PORT }}
        script_stop: true
        envs: TARGET,ENV,SHA
        script: |
          cd $TARGET/git-actions
          git checkout master
          git clean -df
          git checkout -- .
          git pull origin master
          echo $ENV > .env
          echo $SHA > sha.txt
          npm install
          pm2 reload ecosystem.config.js
