name: App Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      env:
        ENV: ${{ secrets.ENV }}
        TARGET: ${{ secrets.TARGET }}
        SHA: ${{ GITHUB_SHA }}
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.REMOTE_PORT }}
        script_stop: true
        envs: TARGET,ENV,SHA
        script: |
          cd $TARGET/git-actions
          git checkout master
          git clean -df
          git checkout -- .
          git pull origin master
          echo $ENV > .env
          echo "\nSHA=$SHA" >> .env
          npm install
          pm2 reload ecosystem.config.js
