name: Deploy to Server
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Haciendo deploy
    steps:
      - name: Instalando node 10.19.0
        uses: actions/setup-node@v1
        with:
          node-version: 10.19.0
      - run: npm install
      - run: npm run ci
      - run: rm -rf .git
      - run: rm -rf .github
      - run: 'echo "$SSH_KEY" > key'
        shell: bash
        env:
          SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
      - run: 'echo "$ENV" > .env'
        shell: bash
        env:
          ENV: ${{ secrets.ENV }}
      - run: sudo chmod 700 ./key
      - name: Rsync to Server
        run: rsync -rav -e "ssh -i ./key -p ${{ secrets.REMOTE_PORT }} -oStrictHostKeyChecking=no" --progress --exclude={"node_modules","key"} . ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.TARGET }}
      - name: 'Run migrations'
        run: ssh -i ./key -p ${{ secrets.REMOTE_PORT }} ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "cd ${{ secrets.TARGET }}; npm start"